---
title: "process_nhanes"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(mgcv)
library(refund)
library(haven)
library(fastDummies)
```

### Download and process accelerometry data

<https://wwwn.cdc.gov/nchs/nhanes/>

```{r}
names_accel_xpt <- c('https://ftp.cdc.gov/pub/NHANES/LargeDataFiles/PAXMIN_G.xpt', 'https://ftp.cdc.gov/pub/NHANES/LargeDataFiles/PAXMIN_H.xpt')
names_short <- c('PAXMIN_G.xpt', 'PAXMIN_H.xpt')
```

```{r}
# sim.data1 <- read_xpt(names_short[1])
# write_rds(sim.data1, '2011_2012_min_data.rds')
# sim.data2 <- read_xpt(names_short[2])
# write_rds(sim.data2, '2013_2014_min_data.rds')
```

```{r}
sim.data1 <- read_rds('2011_2012_min_data.rds')
sim.data2 <- read_rds('2013_2014_min_data.rds')
df_list <- list(sim.data1, sim.data2)
for(i in seq(1,2)){
  sim.data <- df_list[[i]]
  qc_check <- sim.data %>%
    group_by(SEQN, PAXDAYM) %>%
    filter(n() == 1440) %>%
    summarise(non_wear_hrs = sum(PAXPREDM == 3)/60, num_qual_flags = sum(PAXQFM > 0 ))


   mims_wide <- sim.data %>%
      group_by(SEQN, PAXDAYM) %>%
      filter(n() == 1440) %>%
    #take only full days of data
      mutate(min = seq(1, 1440)) %>%
      pivot_wider(id_cols = c('SEQN', 'PAXDAYM'), values_from = 'PAXMTSM', names_from = min) %>%
     full_join(qc_check) %>%
     filter(non_wear_hrs < 14 & num_qual_flags < 14*60) %>%
     dplyr::select(-non_wear_hrs, -num_qual_flags)

   day_count <- mims_wide %>%
      ungroup() %>%
      group_by(SEQN) %>%
      summarise(n = n())
   
   mims_id <- mims_wide %>%
     ungroup() %>%
     left_join(day_count) %>%
     filter(n == 7) %>%
     dplyr::select(SEQN, PAXDAYM)
   write_rds(mims_id, paste0('mims_id_', i, '.rds'))

   mims_agg <- mims_wide %>%
     ungroup() %>%
     dplyr::select(-PAXDAYM) %>%
     left_join(day_count) %>%
     filter(n == 7) %>%
     dplyr::select(-n) %>%
     group_by(SEQN) %>%
     summarise_at(seq(1, 1440), mean)
   write_rds(mims_agg, paste0('mims_agg_', i, '.rds'))

}
```

```{r}
mims_df <- rbind(read_rds('mims_agg_1.rds'), read_rds('mims_agg_2.rds'))
```

### Covariate information

<https://wwwn.cdc.gov/nchs/nhanes/search/variablelist.aspx?Component=Demographics&Cycle=2011-2012>

<https://wwwn.cdc.gov/nchs/nhanes/search/variablelist.aspx?Component=Demographics&Cycle=2013-2014>

#### Demographics

```{r}
covs_201112 <- read_xpt('https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2011/DataFiles/DEMO_G.xpt') %>%
  dplyr::select(SEQN, RIDRETH3, RIAGENDR, RIDAGEYR, DMDEDUC2)
covs_201314 <- read_xpt('https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2013/DataFiles/DEMO_H.xpt') %>%
  dplyr::select(SEQN, RIDRETH3, RIAGENDR, RIDAGEYR, DMDEDUC2)

covs <- rbind(covs_201112, covs_201314) %>%
  rename(race = RIDRETH3, gender = RIAGENDR, age = RIDAGEYR) %>%
  dummy_cols(select_columns = 'race', remove_first_dummy = TRUE) %>%
  mutate(gender = ifelse(gender == 1, 0, 1)) %>%
  mutate(educ = ifelse(is.na(DMDEDUC2) | DMDEDUC2 == 7 | DMDEDUC2 == 9, NA,
                       ifelse(DMDEDUC2 == 1, 1,
                              ifelse(DMDEDUC2 ==2, 2, 3)))) %>%
  dummy_cols(select_columns = 'educ', remove_first_dummy = TRUE) %>%
  dplyr::select(-race,-DMDEDUC2, -educ, -educ_NA)
```

#### BMI

```{r}
bmi_201112 <- read_xpt('https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2011/DataFiles/BMX_G.xpt') %>%
  dplyr::select(SEQN, BMXBMI)
bmi_201314 <- read_xpt('https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2013/DataFiles/BMX_H.xpt') %>%
  dplyr::select(SEQN, BMXBMI)

bmi <- rbind(bmi_201112, bmi_201314) %>%
  rename(bmi = BMXBMI)
```

#### Medical Conditions

```{r}
med_conditions_201112 <- read_xpt('https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2011/DataFiles/MCQ_G.xpt') %>%
  dplyr::select(SEQN, MCQ160B, MCQ160C, MCQ160E, MCQ160F)
med_conditions_201314 <- read_xpt('https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2013/DataFiles/MCQ_H.xpt') %>%
  dplyr::select(SEQN, MCQ160B, MCQ160C, MCQ160E, MCQ160F)

med_cond <- rbind(med_conditions_201112, med_conditions_201314) %>%
  mutate_at(c('MCQ160B', 'MCQ160C', 'MCQ160E', 'MCQ160F'), ~ifelse(is.na(.x) | .x == 7 | .x == 9, NA, ifelse(.x == 2, 0, 1))) %>%
  rename(chf = MCQ160B, chd = MCQ160C, heart_attack = MCQ160E, stroke = MCQ160F)
```

#### Diabetes

```{r}
diabetes201112 <- read_xpt('https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2011/DataFiles/DIQ_G.xpt') %>%
  dplyr::select(SEQN, DIQ010)

diabetes201314 <- read_xpt('https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2013/DataFiles/DIQ_H.xpt')  %>%
  dplyr::select(SEQN, DIQ010)

diabetes <- rbind(diabetes201112, diabetes201314) %>%
  mutate(diabetes = ifelse(is.na(DIQ010) | DIQ010 == 7 | DIQ010 == 9, NA, ifelse(DIQ010 ==1, 1, 0))) %>%
  dplyr::select(-DIQ010)
```

#### Current health status

```{r}
chs_201112 <-read_xpt('https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2011/DataFiles/HSQ_G.xpt') %>%
  dplyr::select(SEQN, HSD010)

chs_201314  <-read_xpt('https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2013/DataFiles/HSQ_H.xpt') %>%
  dplyr::select(SEQN, HSD010) 

chs <- rbind(chs_201112, chs_201314) %>%
  mutate(health_cond = ifelse(is.na(HSD010) | HSD010 == 7 | HSD010 == 9, NA, HSD010)) %>%
  dummy_cols(select_columns = 'health_cond', remove_first_dummy = TRUE) %>%
  dplyr::select(-health_cond, -health_cond_NA, -HSD010)
```

#### Alcohol consumption

```{r}
alc_201112 <- read_xpt('https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2011/DataFiles/ALQ_G.xpt') %>%
  dplyr::select(SEQN, ALQ101, ALQ110, ALQ120Q, ALQ130) 
alc_201314 <- read_xpt('https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2013/DataFiles/ALQ_H.xpt') %>%
  dplyr::select(SEQN, ALQ101, ALQ110, ALQ120Q,ALQ130) 

alc <- rbind(alc_201112, alc_201314 ) %>%
  left_join(covs %>% dplyr::select(SEQN, gender), by = 'SEQN') %>%
  mutate(alc101_NA = ifelse(is.na(ALQ101) | ALQ101 == 7 | ALQ101 == 9,1, 0),
         alc110_NA = ifelse(is.na(ALQ110) | ALQ110 == 7 | ALQ110 == 9,1, 0),
         alc120_NA = ifelse(is.na(ALQ120Q) | ALQ120Q == 777 | ALQ120Q == 999,1, 0),
         alc130_NA = ifelse(is.na(ALQ130) | ALQ130 == 777 | ALQ130 == 999,1, 0)) %>%
  mutate(drink_never = ifelse(alc101_NA ==1 | (ALQ101 == 2 & alc110_NA == 1) |(ALQ101 == 1 & alc120_NA == 1),NA, ifelse(ALQ101 == 2 & ALQ110 ==2, 1, 0)),
         drink_former = ifelse(alc101_NA ==1 | (ALQ101 == 2 & alc110_NA == 1) | (ALQ101 == 1 & alc120_NA == 1),NA, ifelse(ALQ101 == 2 & ALQ110 ==1, 1, 0)),
         drink_mod = ifelse(alc101_NA ==1 | (ALQ101 == 2 & alc110_NA == 1) | (ALQ101 == 1 & alc120_NA == 1),NA, ifelse(drink_never == 1 | drink_former == 1, 0, ifelse(alc130_NA == 1 & alc120_NA == 0,1, ifelse(ALQ130 <= 1 & gender == 1, 1, ifelse(ALQ130 <= 2 & gender == 0,1, 0))))),
        drink_heavy = ifelse(alc101_NA ==1 | (ALQ101 == 2 & alc110_NA == 1) | (ALQ101 == 1 & alc120_NA == 1),NA, ifelse(drink_never == 1 | drink_former == 1, 0, ifelse(alc130_NA == 1 & alc120_NA == 0,0, 
                            ifelse(ALQ130 > 1 & gender == 1, 1,
                                   ifelse(ALQ130 > 2 & gender == 0,1, 0)))))) %>%
  dplyr::select(-ALQ101, -ALQ110,-ALQ120Q, -ALQ130, -gender, -drink_never, -alc101_NA, -alc120_NA, -alc110_NA, -alc130_NA)
```

#### Cigarette smoking

```{r}
smoking_201112 <- read_xpt('https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2011/DataFiles/SMQ_G.xpt') %>%
  dplyr::select(SEQN, SMQ020, SMQ040)
smoking_201314 <- read_xpt('https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2013/DataFiles/SMQ_H.xpt') %>%
  dplyr::select(SEQN, SMQ020, SMQ040)

smoking <- rbind(smoking_201112, smoking_201314) %>%
  mutate(smoke20_NA = ifelse(is.na(SMQ020) | SMQ020 == 7 | SMQ020 == 9, 1,0),
         smoke40_NA = ifelse(is.na(SMQ040) | SMQ040 == 7 | SMQ040 == 9, 1,0)) %>%
  mutate(smoke_never = ifelse(smoke20_NA ==1 | (SMQ020 ==1 & smoke40_NA == 1), NA, ifelse(SMQ020 == 2, 1, 0)),
         smoke_former = ifelse(smoke20_NA ==1 | (SMQ020 == 1& smoke40_NA == 1), NA, ifelse(smoke_never == 1, 0, ifelse(SMQ040 == 3, 1, 0)))) %>%
  dplyr::select(-SMQ020, -SMQ040, -smoke20_NA, -smoke40_NA)
```

#### Physical functioning

```{r}
phys_201112 <- read_xpt('https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2011/DataFiles/PFQ_G.xpt') %>%
  dplyr::select(SEQN, PFQ061B, PFQ061C, PFQ054)
phys_201314 <- read_xpt('https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2013/DataFiles/PFQ_H.xpt') %>%
  dplyr::select(SEQN, PFQ061B, PFQ061C, PFQ054)

phys <- rbind(phys_201112, phys_201314) %>%
  mutate(pfq = ifelse(is.na(PFQ054)| PFQ054 == 7| PFQ054 == 9, NA, ifelse(PFQ054==1,1, 0))) %>%
  dplyr::select(-PFQ061B, -PFQ061C, -PFQ054)
```

### Mortality

<https://www.cdc.gov/nchs/linked-data/mortality-files/>

<https://ehsanx.github.io/EpiMethods/accessing7.html>

```{r}
mort201112 <- read_fwf(
  file = 'NHANES_2011_2012_MORT_2019_PUBLIC.dat',
  col_types = "iiiiiiii",
  fwf_cols(SEQN = c(1,6), 
           eligstat = c(15,15),
           mortstat = c(16,16),
           ucod_leading = c(17,19),
           diabetes = c(20,20),
           hyperten = c(21,21),
           permth_int = c(43,45),
           permth_exm = c(46,48)),
  na = c("", "."))


mort201314 <- read_fwf(
  file = 'NHANES_2013_2014_MORT_2019_PUBLIC.dat',
  col_types = "iiiiiiii",
  fwf_cols(SEQN = c(1,6), 
           eligstat = c(15,15),
           mortstat = c(16,16),
           ucod_leading = c(17,19),
           diabetes = c(20,20),
           hyperten = c(21,21),
           permth_int = c(43,45),
           permth_exm = c(46,48)),
  na = c("", "."))

mort <- rbind(mort201112, mort201314) %>%
  mutate(mort5yr= ifelse(is.na(mortstat), NA, ifelse(mortstat ==0, 0, ifelse(mortstat ==1 & permth_int > 60, 0, 1)))) %>%
  dplyr::select(SEQN, mort5yr)
```

## Join all data

```{r}
all_df <- mims_df %>%
  left_join(mort, by = 'SEQN') %>%
  left_join(covs, by = 'SEQN') %>%
  left_join(bmi, by = 'SEQN') %>%
  left_join(med_cond, by = 'SEQN') %>%
  left_join(diabetes, by = 'SEQN') %>%
  left_join(chs, by = 'SEQN') %>%
  left_join(alc, by = 'SEQN') %>%
  left_join(smoking, by = 'SEQN') %>%
  left_join(phys, by = 'SEQN') %>%
  drop_na()
#write_rds(all_df, 'saved_results/nhanes_real_data_clean.rds')
```
